#server:
#  port: 8040
#spring:
#  application:
#    name: "cards"
#  profiles:
#    active: "prod"
#  datasource:
#    url: jdbc:mysql://localhost:3330/cardsdb
#    username: root
#    password: root
#  jpa:
#    show-sql: true
#  sql:
#    init:
#      mode: always
#  config:
#    import: "optional:configserver:http://localhost:8010/"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"

server:
  port: 8040
spring:
  application:
    name: "cards"
  profiles:
    active: "default"
  datasource:
    url: jdbc:mysql://cardsdb:3306/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://configserver:8010/"
  rabbitmq:
    host: "rabbitmq"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true



eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: "http://eurekaserver:8761/eureka/"

info:
  app:
    name: "cards"
    description: "Cards Service"
    version: "1.0.0"