spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://configserver:8010/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false  # Changed from true to false
      httpclient:
        connect-timeout: 1000
        response-timeout: 2s
  rabbitmq:
    host: "rabbitmq"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Gateway Service"
    version: "1.0.0"

logging:
  level:
    net.abderrahimself.gatewayserver.filters: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000