spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://configserver:8010/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false  # Changed from true to false
  rabbitmq:
    host: "rabbitmq"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Gateway Service"
    version: "1.0.0"

logging:
  level:
    net.abderrahimself.gatewayserver.filters: DEBUG