#services:
#  network-deploy-service:
#    networks:
#      - abderrahimself
#
#  microservice-base-config:
#    extends:
#      service: network-deploy-service
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#    environment:
#      SPRING_RABBITMQ_HOST: "rabbitmq"
#
#  microservice-configserver-config:
#    extends:
#      service: microservice-base-config
#    environment:
#      SPRING_PROFILES_ACTIVE: qa
#      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

services:
  network-deploy-service:
    networks:
      - abderrahimself

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 800m  # Slightly more than default for testing
        reservations:
          memory: 256m
    environment:
      SPRING_RABBITMQ_HOST: "rabbitmq"

  microservice-db-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  microservice-configserver-config:
    extends:
      service: microservice-db-config
    environment:
      SPRING_PROFILES_ACTIVE: qa
      SPRING_CONFIG_IMPORT: configserver:http://configserver:7010/