#services:
#  configserver:
#    image: "abderrahimself/configserver:s6"
#    container_name: configserver-ms
#    ports:
#      - "8071:8071"
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
#    healthcheck:
#      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 10s
#    extends:
#      file: common-config.yml
#      service: network-deploy-service
#
#  accounts:
#    image: "abderrahimself/accounts:s6"
#    container_name: accounts-ms
#    ports:
#      - "8080:8080"
#    depends_on:
#      configserver:
#        condition: service_healthy
#    environment:
#      SPRING_APPLICATION_NAME: "accounts"
#    extends:
#      file: common-config.yml
#      service: microservice-configserver-config
#
#  loans:
#    image: "abderrahimself/loans:s6"
#    container_name: loans-ms
#    ports:
#      - "8090:8090"
#    depends_on:
#      configserver:
#        condition: service_healthy
#    environment:
#      SPRING_APPLICATION_NAME: loans
#    extends:
#      file: common-config.yml
#      service: microservice-configserver-config
#
#  cards:
#    image: "abderrahimself/cards:s6"
#    container_name: cards-ms
#    ports:
#      - "9000:9000"
#    depends_on:
#      configserver:
#        condition: service_healthy
#    environment:
#      SPRING_APPLICATION_NAME: cards
#    extends:
#      file: common-config.yml
#      service: microservice-configserver-config
#
#  rabbitmq:
#    image: "rabbitmq:4-management"
#    hostname: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    healthcheck:
#      test: rabbitmq-diagnostics check_port_connectivity
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 5s
#    extends:
#      file: common-config.yml
#      service: network-deploy-service
#
#networks:
#  abderrahimself:
#    driver: "bridge"

services:
  configserver:
    image: "abderrahimself/configserver:s7"
    container_name: configserver-ms-qa
    ports:
      - "7010:7010"
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:7010/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: network-deploy-service

  accounts:
    image: "abderrahimself/accounts:s7"
    container_name: accounts-ms-qa
    ports:
      - "7020:7020"
    depends_on:
      configserver:
        condition: service_healthy
      accountsdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "abderrahimself/loans:s7"
    container_name: loans-ms-qa
    ports:
      - "7030:7030"
    depends_on:
      configserver:
        condition: service_healthy
      loansdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: loans
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "abderrahimself/cards:s7"
    container_name: cards-ms-qa
    ports:
      - "7040:7040"
    depends_on:
      configserver:
        condition: service_healthy
      cardsdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: cards
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  # Database Services
  accountsdb:
    image: mysql:latest
    container_name: accountsdb-qa
    ports:
      - "2310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accountsdb
    volumes:
      - accountsdb_qa_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    extends:
      file: common-config.yml
      service: network-deploy-service

  loansdb:
    image: mysql:latest
    container_name: loansdb-qa
    ports:
      - "2320:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loansdb
    volumes:
      - loansdb_qa_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    extends:
      file: common-config.yml
      service: network-deploy-service

  cardsdb:
    image: mysql:latest
    container_name: cardsdb-qa
    ports:
      - "2330:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cardsdb
    volumes:
      - cardsdb_qa_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    extends:
      file: common-config.yml
      service: network-deploy-service

  # phpMyAdmin Services
  phpmyadmin-accounts:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-accounts-qa
    ports:
      - "7110:80"
    environment:
      PMA_HOST: accountsdb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      accountsdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: network-deploy-service

  phpmyadmin-loans:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-loans-qa
    ports:
      - "7120:80"
    environment:
      PMA_HOST: loansdb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      loansdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: network-deploy-service

  phpmyadmin-cards:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-cards-qa
    ports:
      - "7130:80"
    environment:
      PMA_HOST: cardsdb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      cardsdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: network-deploy-service

  rabbitmq:
    image: "rabbitmq:4-management"
    hostname: rabbitmq-qa
    container_name: rabbitmq-qa
    ports:
      - "4672:5672"
      - "14672:15672"
    volumes:
      - rabbitmq_qa_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

volumes:
  accountsdb_qa_data:
  loansdb_qa_data:
  cardsdb_qa_data:
  rabbitmq_qa_data:

networks:
  abderrahimself:
    driver: "bridge"